package put.inf154030.zwaar

import put.inf154030.zwaar.entities.Exercise

object Exercises {
    val exercisesList = listOf(
        Exercise(0, "Barbell Squats", 1),
        Exercise(0, "Barbell Bench Press", 1),
        Exercise(0, "Barbell Deadlift", 1),
        Exercise(0, "Dumbbell Bench Press", 2),
        Exercise(0, "Dumbbell Shoulder Press", 2),
        Exercise(0, "Dumbbell Lunges", 2),
        Exercise(0, "Cleans", 3),
        Exercise(0, "Snatches", 3),
        Exercise(0, "Presses", 3),
        Exercise(0, "Get-ups", 3),
        Exercise(0, "Windmill", 3),
        Exercise(0, "Clean and Press", 3),
        Exercise(0, "Swings", 3),
        Exercise(0, "Biceps Curl", 4),
        Exercise(0, "French Press", 4),
        Exercise(0, "Barbell pull-over", 4),
        Exercise(0, "Resistance Band Squats", 5),
        Exercise(0, "Resistance Band Rows", 5),
        Exercise(0, "Resistance Band Chest Press", 5),
        Exercise(0, "Bench Press (Chest)", 6),
        Exercise(0, "Close Grip Bench Press (Triceps)", 6),
        Exercise(0, "Chest Flyes", 7),
        Exercise(0, "Bench Press with a machine", 8),
        Exercise(0, "Chest Press", 9),
        Exercise(0, "Power Rack Squats", 10),
        Exercise(0, "Power Rack Deadlift", 10),
        Exercise(0, "Power Rack Shoulder Press", 10),
        Exercise(0, "Power Rack Bench Press", 10),
        Exercise(0, "Leg Presses", 11),
        Exercise(0, "Calf Presses", 11),
        Exercise(0, "Hack squat", 12),
        Exercise(0, "Smith Machine Squat", 13),
        Exercise(0, "Smith Machine Bench Press", 13),
        Exercise(0, "Smith Machine Shoulder Press", 13),
        Exercise(0, "Smith Machine Bent-over Row", 13),
        Exercise(0, "Smith Machine Deadlift", 13),
        Exercise(0, "Smith Machine High Pulls", 13),
        Exercise(0, "Smith Machine Triceps Extension", 13),
        Exercise(0, "Leg Extensions", 14),
        Exercise(0, "Leg Curls", 15),
        Exercise(0, "Seated Calf Raises", 16),
        Exercise(0, "Standing Calf Raise", 17),
        Exercise(0, "Lat pulldown movement", 18),
        Exercise(0, "Cable ab crunches", 18),
        Exercise(0, "Triceps press", 18),
        Exercise(0, "Biceps curl", 18),
        Exercise(0, "Pull ups", 19),
        Exercise(0, "Chin ups", 19),
        Exercise(0, "T-bar row", 20),
        Exercise(0, "Seated rows", 21),
        Exercise(0, "Erector spinae", 22),
        Exercise(0, "Hyper-extension", 22),
        Exercise(0, "Incline sit up", 22),
        Exercise(0, "Preacher Curls", 23),
        Exercise(0, "Spider Curls", 23),
        Exercise(0, "Machine Biceps Curls", 24),
        Exercise(0, "Triceps Extensions", 25),
        Exercise(0, "Shoulder/Military Presses", 26),
        Exercise(0, "Lateral Raises", 27),
        Exercise(0, "Machine Crunches", 28),
        Exercise(0, "Ab wheel roll-outs", 29),
        Exercise(0, "Wall slams", 30),
        Exercise(0, "High throws", 30),
        Exercise(0, "Floor slams", 30),
        Exercise(0, "Tossing/catching", 30),
        Exercise(0, "Plank", 31),
        Exercise(0, "Abdominal crunch", 31),
        Exercise(0, "Hyperextensions", 31),
        Exercise(0, "Push-ups", 31),
        Exercise(0, "Wall-squats", 31),
        Exercise(0, "Self-myofascial release", 32),
        Exercise(0, "Indoor rowing", 33),
        Exercise(0, "Low impact all-body cardiovascular conditioning", 34),
        Exercise(0, "Indoor pedaling", 35),
        Exercise(0, "Indoor recumbent biking", 36),
        Exercise(0, "Standing", 37),
        Exercise(0, "Yoga", 37),
        Exercise(0, "Pedal", 38),
        Exercise(0, "Climbing", 39),
    )
}